name: msdocviewer-parser

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - name: 设置python版本
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行脚本
        run: |
          python run_me_first.py --overwrite
      
      - name: 压缩文件夹
        run: zip -r apis_md.zip ./apis_md
      
      - name: upload-artifact
        uses: actions/upload-artifact@v3.1.3
        with:
            name: apis_md.zip
            path: ./apis_md.zip
          
      - name: 发布
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Auto Build"
          files: ./apis_md.zip

